- hosts: localhost
  become: true
  tasks:
  - name: Fish PPA version 3
    apt_repository:
      validate_certs: no
      repo: 'ppa:fish-shell/release-3'
      state: present
  - name: Install packages
    apt: 
      name: "{{packages}}"
      state: present
      update_cache: yes
    vars:  
      packages:
        - build-essential
        - fish
        - git
        - htop
        - mc
        - neofetch
        - tmux
        - xclip

  - name: Clone termite git repository
    git:
      clone: true
      dest: "/home/{{ ansible_user }}/termite"
      force: true
      recursive: true
      repo: https://github.com/thestinger/termite.git
  - name: Clone vte-ng git repository
    git:
      clone: true
      dest: "/home/{{ ansible_user }}/vte-ng"
      force: true
      repo: https://github.com/thestinger/vte-ng.git
  - name: Install packages necessary to compile termite
    apt:
      name: "{{packages}}"
      state: present
    vars:
      packages:
        - g++
        - libgtk-3-dev
        - gtk-doc-tools
        - gnutls-bin
        - valac
        - intltool
        - libpcre2-dev
        - libglib3.0-cil-dev
        - libgnutls28-dev
        - libgirepository1.0-dev
        - libxml2-utils
        - gperf

